// al final de tot hi ha un export
function llista_rutes() {
	var rutes = [
		{"zona":"TransPirenaica","id":"transpirenaica","rutes":[
			{"ruta":"Transpirinenca. Bonansa-Escalona", "fitxer":"TP_09_bonansa-escalona.gpx"},
			{"ruta":"Transpirinenca. Fiscal-Aurín", "fitxer":"TP_11_fiscal-aurin.gpx"},
			{"ruta":"Transpirinenca. Etxalar-Hondarribia", "fitxer":"TP_16_etxalar-hondarribia.gpx"},
			{"ruta":"Transpirinenca. Planoles-Bagà", "fitxer":"TP_04_planoles-baga.gpx"},
			{"ruta":"Transpirinenca. Izaba-Roncesvalles", "fitxer":"TP_14_izaba-roncesvalles.gpx"},
			{"ruta":"Transpirinenca. Albanyà-Camprodon", "fitxer":"TP_02_albanya-camprodon.gpx"},
			{"ruta":"Transpirinenca. Camprodon-Planoles", "fitxer":"TP_03_camprodon-planoles.gpx"},
			{"ruta":"Transpirinenca. Espui-Bonansa", "fitxer":"TP_08_espui-bonansa.gpx"},
			{"ruta":"Transpirinenca. Bagà-Noves de Segre", "fitxer":"TP_05_bagà-noves_de_segre.gpx"},
			{"ruta":"Transpirinenca. Escalona-Fiscal", "fitxer":"TP_10_escalona-fiscal.gpx"},
			{"ruta":"Transpirinenca. Echo-Izaba", "fitxer":"TP_13_echo-izaba.gpx"},
			{"ruta":"Transpirinenca. Noves de Segre-Llavorsí", "fitxer":"TP_06_noves_de_segre-llavorsi.gpx"},
			{"ruta":"Transpirinenca. Roncesvalles-Etxalar", "fitxer":"TP_15_roncesvalles-etxalar.gpx"},
			{"ruta":"Transpirinenca. Aurín-Echo", "fitxer":"TP_12_aurín-echo.gpx"},
			{"ruta":"Transpirinenca. Llavorsí-Espui", "fitxer":"TP_07_llavorsí-espui.gpx"},
			{"ruta":"Transpirinenca. Llançà-Albanyà", "fitxer":"TP_01_llança-albanya.gpx"}
		]},
		{"zona":"Sant Feliu","id":"sant_feliu","rutes":[
			{"ruta":"Sant Feliu de C-Riera de Caldes-Riu Besós-Sta Coloma de Gr", "fitxer":"st_feliu_de_c-sta_coloma_de_gr.gpx"},
			{"ruta":"St Feliu de Codines-Gallifa-El Farell-Caldes", "fitxer":"st_feliu_codines_gallifa_farell_caldes.gpx"},
			{"ruta":"Terrassa-Sant Feliu de Codines", "fitxer":"Terrassa-Sant_Feliu_de_Codines.gpx"},
			{"ruta":"Sant Feliu de Codines-Sabadell", "fitxer":"sant_feliu_codines_sabadell.gpx"},
			{"ruta":"Centelles - Sant Feliu", "fitxer":"centelles_stfeliu.gpx"},
			{"ruta":"TODO St Feliu corriols", "fitxer":"todo-st_feliu-corriols.gpx"},
			{"ruta":"St Feliu de Codines-Tenes-Besós-BCN", "fitxer":"st_feliu_codines-tenes-besos-bcn.gpx"},
			{"ruta":"ToDo-Vacarisses-Sant Feliu de C-2", "fitxer":"todo-vacarisses-st_feliu_codines-2.gpx"},
			{"ruta":"Sant Feliu de Codines-Terrassa", "fitxer":"Sant_feliu_codines-Terrassa.gpx"},
			{"ruta":"Centelles-Collsuspina-Popa-St Feliu de Codines", "fitxer":"Centelles-Collsuspina-Popa-St_Feliu_de_Codines.gpx"},
			{"ruta":"Barcelona - Sant Feliu", "fitxer":"bcn_stfeliu_1.gpx"},
			{"ruta":"Vacarisses-Obac-St Llorenc Savall-Gallifa-St Feliu", "fitxer":"Vacarisses-Obac-St_Llorenc_Savall-Gallifa-St_Feliu.gpx"},
			{"ruta":"Sant Feliu-La Garriga", "fitxer":"st_feliu-la_garriga.gpx"},
			{"ruta":"St Feliu-Volta a la Popa", "fitxer":"st_feliu_cod-volta_a_la_popa.gpx"},
			{"ruta":"Centelles-Collsuspina-Sta Coloma S-Castellterçol-St Julià Uixols-St Feliu", "fitxer":"centelles-collsus-sta_col_sasserra-castelltercol-uixols.gpx"},
			{"ruta":"Castellterçol, Sant Julià d'Úixols i Sant Quirze Safaja", "fitxer":"castelltercol-sant-julia-duixols-i-sant-quirze-safaja.gpx"},
			{"ruta":"St_Feliu_Codines-Poses-Matafaluga-Gallifa", "fitxer":"St_Feliu_Codines-Poses-Matafaluga-Gallifa.gpx"},
			{"ruta":"Sant Feliu de Codines-Caldes-Sentmenat-Castellar-St Sebastià de Montmajor", "fitxer":"st_feliu-caldes-castellar-montmajor.gpx"},
			{"ruta":"Volta per Sant Feliu 1", "fitxer":"volta_per_st_feliu_1.gpx"},
			{"ruta":"Sant Feliu-La Garriga v2", "fitxer":"st_feliu-la_garriga_v2.gpx"},
			{"ruta":"Sta Coloma Gr-Vall del Tenes-St Feliu", "fitxer":"sta_coloma-tenes-st_feliu.gpx"},
			{"ruta":"St Feliu-Unyó-Ullà", "fitxer":"st_miquel_del_fai_uno_ulla.gpx"}
		]},
		{"zona":"Berguedà","id":"bergueda","rutes":[
			{"ruta":"Cercs - Peguera - Cercs", "fitxer":"cercs-peguera.gpx"},
			{"ruta":"Les Rovires de Baix 2", "fitxer":"les_rovires_de_baix_2.gpx"},
			{"ruta":"ToDo-Montclar", "fitxer":"todo-montclar.gpx"},
			{"ruta":"ToDo - El Collet-Vallcebre-Coll de Pradell-Saldes-Riera Saldes", "fitxer":"todo-el_collet-vallcebre-coll_de_pradell-saldes-riera_saldes.gpx"},
			{"ruta":"ToDo - Bagà-Gréixer-Escriu-Pendís-Bellver", "fitxer":"todo-baga-greixer-escriu-pendis-bellver.gpx"},
			{"ruta":"ToDo-Sant Jaume de Frontanyà - Gombrèn v2", "fitxer":"todo-gombren-sant-jaume-de-frontanya-gombren_v2.gpx"},
			{"ruta":"ToDo-Baix_Berguedà", "fitxer":"todo-baix_bergueda.gpx"},
			{"ruta":"ToDo - st_maurici_la_quar-portella", "fitxer":"todo-st_maurici_la_quar-portella.gpx"},
			{"ruta":"ToDo - Ripoll-Les Rovires", "fitxer":"todo-ripoll-les_rovires.gpx"},
			{"ruta":"ToDo - Coll de Pal-Pobla de Lillet", "fitxer":"todo-coll_de_pal-pobla_de_lillet.gpx"},
			{"ruta":"ToDo-Sant Jaume de Frontanyà - Gombrèn v1", "fitxer":"todo-gombren-sant-jaume-de-frontanya-gombren_v1.gpx"},
			{"ruta":"ToDo - Volta als Rasos de Tubau", "fitxer":"todo-volta_rasos_tubau.gpx"},
			{"ruta":"Ripoll-Les Rovires de Baix", "fitxer":"ripoll-les_rovires_de_baix.gpx"},
			{"ruta":"La Sala-Sta Cecília de Riutort-Coll Cerqueda-Coll Portelletes", "fitxer":"la_sala-sta_cecilia_riutort-coll_cerqueda-coll_portelletes.gpx"},
			{"ruta":"La Catllaràs 2018", "fitxer":"la-catllaras-2018.gpx"},
			{"ruta":"Les Rovires-Borredà a peu", "fitxer":"les_rovires-borreda-a_peu.gpx"},
			{"ruta":"ToDo-morral_de_montsent_el_banc", "fitxer":"todo-morral_de_montsent_el_banc.gpx"},
			{"ruta":"ToDo - Volta a la Serra d'Ensija", "fitxer":"todo-volta_serra_ensija.gpx"},
			{"ruta":"Riutort - Pobla de Lillet", "fitxer":"riutort_pobla_de_lillet.gpx"},
			{"ruta":"ToDo - Pobla de Lillet-Gombrèn-Castellar de n'Hug", "fitxer":"todo-pobla_lillet-gombren-castellar_nhug.gpx"},
			{"ruta":"ToDo - Llacuna-Queralt-Sant Martí de Tous", "fitxer":"todo-llacuna-queralt-st_marti_de_tous.gpx"},
			{"ruta":"ToDo - Lluçanès Feréstec 2019 llarga", "fitxer":"todo-llucanes-ferestec-2019-llarga.gpx"},
			{"ruta":"Les Rovires de Baix 1", "fitxer":"les_rovires_de_baix_1.gpx"},
			{"ruta":"ToDo - Coll de Pradell - Volta als Cingles de Costafreda", "fitxer":"todo-coll_pradell-volta_cingles_costafreda.gpx"},
			{"ruta":"ToDo - Bagà-Gisclareny-Coll de Bauma-El Collell-Riera de Saldes", "fitxer":"todo-baga-gisclareny-coll_bauma-el_collell-riera_saldes.gpx"},
			{"ruta":"ToDo - Coll de Pal-Gavarrós-Espelt", "fitxer":"todo-coll_de_pal-gavarros-espelt.gpx"},
			{"ruta":"ToDo - Casserres-Montclar", "fitxer":"todo-Casserres-Montclar.gpx"},
			{"ruta":"ToDo - Camprodon-Les Rovires", "fitxer":"todo-camprodon-les_rovires.gpx"},
			{"ruta":"Les Rovires de Baix 3", "fitxer":"les_rovires_de_baix_3.gpx"}
		]},
		{"zona":"Barcelona","id":"barcelona","rutes":[
			{"ruta":"Vallcarca-Tibidabo-PiXandri-Sol-i-aire", "fitxer":"vallcarca-tibidabo-pixandri-sol-i-aire.gpx"},
			{"ruta":"Baixador de Vallvidrera-Sitges", "fitxer":"baixador_vallvidrera-sitges.gpx"},
			{"ruta":"Volta per Collserola 2", "fitxer":"volta_per_collserola_2.gpx"},
			{"ruta":"Volta per Collserola 4 corriols", "fitxer":"volta_per_collserola_4-corriols.gpx"},
			{"ruta":"ToDo-Volta per Collserola 5", "fitxer":"todo-volta_per_collserola_5.gpx"},
			{"ruta":"Mercabarna-Delta del Llobregat", "fitxer":"mercabarna-delta_llobregat.gpx"},
			{"ruta":"Volta per Collserola", "fitxer":"volta_per_collserola_1.gpx"},
			{"ruta":"Poblat Ibèric Puig Castellar", "fitxer":"poblat-iberic-puig-castellar.gpx"},
			{"ruta":"Baixador Vallvidrera-Delta Llobregat", "fitxer":"baixador_vallvidrera_delta_llobregat.gpx"},
			{"ruta":"Integral Carretera de les Aigües 2", "fitxer":"integral_carretera_aigues_2.gpx"},
			{"ruta":"Corriols de la Vall de Sant Just", "fitxer":"corriolada_per_sant_just_desvern.gpx"},
			{"ruta":"La Floresta-Papiol-St Bartomeu-Olèrdola-Baixador Vallvidrera", "fitxer":"la_floresta-papiol-st_bartomeu-olerdola-baixador_vallvidrera.gpx"},
			{"ruta":"Trialerada per Collserola", "fitxer":"trialerada-per-collserola.gpx"},
			{"ruta":"Integral Carretera de les Aigües 3", "fitxer":"integral_carretera_aigues_3.gpx"},
			{"ruta":"Integral Carretera de les Aigües 1", "fitxer":"integral_carretera_aigues_1.gpx"},
			{"ruta":"Baixador_Vallvidrera-Turons_Can_Pasqual-St_Feliu-Passeig_Aigües", "fitxer":"Baixador_Vallvidrera-Turons_Can_Pasqual-St_Feliu-Passeig_Aigües.gpx"},
			{"ruta":"Santa Coloma-El Masnou-Passeig Marítim", "fitxer":"sta_coloma-masnou-pg_maritim.gpx"},
			{"ruta":"Granollers-Sta Coloma de Gr", "fitxer":"granollers-sta_coloma_gr.gpx"},
			{"ruta":"Entreno Collserola Oriental v2", "fitxer":"entreno_collserola_oriental_v2.gpx"},
			{"ruta":"Volta per Collserola-4 ermites", "fitxer":"volta_collserola_4_ermites.gpx"},
			{"ruta":"Volta per Collserola 3", "fitxer":"volta_per_collserola_3.gpx"}
		]},
		{"zona":"Port de la Selva","id":"port_de_la_selva","rutes":[
			{"ruta":"Port de la Selva-Cala Taballera-Mas de Birba-GR92", "fitxer":"port_selva-taballera-birba-gr92.gpx"},
			{"ruta":"Port de la Selva-Vall de la Santa Creu", "fitxer":"port_selva-vall_sta_creu.gpx"},
			{"ruta":"ToDo - Camprodon - Port de la Selva /10-09-11", "fitxer":"todo-camprodon-port-de-la-selva-10-09-11.gpx"},
			{"ruta":"Port de la Selva-3 dòlmens de Taballera", "fitxer":"port_selva-3_dolmens_taballera.gpx"},
			{"ruta":"Port de la Selva-Selva Mar-Coll Bombo-Pla Causa-Puig Sardina-Roses-Mas Romanyac-GR92", "fitxer":"port_selva-coll_bombo-pla_causa-puig_sardina-roses-mas_romanyac-GR9.gpx"},
			{"ruta":"Port de la Selva-St Baldiri-Cala_Taballera-Cadaqués-GR92", "fitxer":"port_selva-st_baldiri-cala_taballera-cadaques-GR92.gpx"},
			{"ruta":"Port de la Selva-carretera de Roses a Coll de Perafita", "fitxer":"port_selva-carretera_roses_perafita.gpx"},
			{"ruta":"Port de la Selva-Selva de Mar-Mas Romanyac-Coll de Perafita-Cadaqués-GR92", "fitxer":"port_selva-selva_mar-mas_romanyac-perafita-cadaques-GR92.gpx"},
			{"ruta":"Port Selva-St Pere de Rodes-Llançà-Puig Tifeu-Garbet", "fitxer":"port_selva-st_pere_de_rodes-llança-puig_tifeu-garbet.gpx"}
		]},
		{"zona":"Altres","id":"altres","rutes":[
			{"ruta":"Montnegre Open MTB 50Km", "fitxer":"montnegreopenmtb_50.gpx"},
			{"ruta":"Monegros Nord", "fitxer":"Monegros-nord.gpx"},
			{"ruta":"Pujada a la Mola", "fitxer":"pujada_a_la_mola.gpx"},
			{"ruta":"La Portals 2013 (4a Volta a Montserrat)", "fitxer":"la-portals-2013-4a-volta-a-la-montanya-de-montserrat-en-btt.gpx"},
			{"ruta":"Aiguafreda-Collformic-Pla de la Calma-Tagamanent", "fitxer":"Aiguafreda-Collformic-Pla_de_la_Calma-Tagamanent.gpx"},
			{"ruta":"Montnegre Open MTB 32Km", "fitxer":"montnegreopenmtb_32.gpx"},
			{"ruta":"Llimiana, Serra Barcedana, Gercles", "fitxer":"llimiana-serra-barcedana-gercles.gpx"},
			{"ruta":"La Sènia-Casetes Velles-Fredes-La Sènia", "fitxer":"la_senia-casetes_velles-fredes-la_senia.gpx"},
			{"ruta":"Maresme Challenge 2013", "fitxer":"maresme_challenge_2013.gpx"},
			{"ruta":"Canovelles-Samalus-Roc Centelles-Cànoves-Marata", "fitxer":"Canovelles-Samalus-Roc_Centelles-Canoves-Marata.gpx"},
			{"ruta":"Monegros Sud", "fitxer":"Monegros-sud.gpx"},
			{"ruta":"Garraf - Begues - Garraf", "fitxer":"garraf-begues-garraf.gpx"},
			{"ruta":"Granollers-Roc de Centelles", "fitxer":"granollers-roc_de_centelles.gpx"},
			{"ruta":"KKH-Karakorum Highway", "fitxer":"KKH.gpx"},
			{"ruta":"Els tres refugis: Coma de Vaca, Ull de Ter, Ras de Carançà", "fitxer":"els_tres_refugis.gpx"},
			{"ruta":"Marxa dels Castells 2010", "fitxer":"marxa_castells.gpx"},
			{"ruta":"Integral megalítica de Vallromanes", "fitxer":"integral_megalitica_vallromanes.gpx"},
			{"ruta":"ToDo - Calaf-Cellers-Quadrells", "fitxer":"todo-calaf-cellers-quadrells.gpx"},
			{"ruta":"ToDo - Calaf-Rubió-Jorba-Copons", "fitxer":"todo-calaf-rubio-jorba-copons.gpx"},
			{"ruta":"Santa Coloma de Gr-Sant Andreu de Llavaneres", "fitxer":"sta_coloma-st_andreu_llavaneres.gpx"}
		]},
		{"zona":"Bagà","id":"baga","rutes":[
			{"ruta":"Bagà-Gréixer-Coll d'Escriu-Empedrats-Bagà", "fitxer":"baga-greixer-escriu-empedrats-baga.gpx"},
			{"ruta":"Volta per Brocà (sector sud)", "fitxer":"volta_broca_sector_sud.gpx"},
			{"ruta":"Bagà-Cap del Tossal", "fitxer":"baga-cap_del_tossal.gpx"},
			{"ruta":"Coll de Pal-Comafloriu-Xalet Coll de Pal", "fitxer":"coll_pal-comafloriu-xalet_coll_de_pal.gpx"},
			{"ruta":"Cambra del Boc", "fitxer":"cambra_del_boc.gpx"},
			{"ruta":"Entreno Bagà 1", "fitxer":"entreno_baga_1.gpx"},
			{"ruta":"Bagà-Collet d'Aïna-El Jou-Fumanya-Vallcebre", "fitxer":"baga-collet_aina-jou-fumanya-vallcebre.gpx"},
			{"ruta":"Bagà-Brocà-Collada Grossa-L'Estret-Riutort", "fitxer":"baga-broca-collada_grossa-estret-riutort.gpx"},
			{"ruta":"Via Nicolau", "fitxer":"via_nicolau.gpx"},
			{"ruta":"Bagà-Coll de Turbians-Coll de la Bena-St Martí del Puig", "fitxer":"baga-coll_turbians-coll_bena-st_marti_puig.gpx"},
			{"ruta":"Cal Cerdanyola-Monnell-Murcurols-El Puig", "fitxer":"cal_cerdanyola-monnell-murcurols-el_puig.gpx"},
			{"ruta":"Transpirenaica en BTT Etapa 5 Bagà-Noves de Segre", "fitxer":"transpirenaica-en-btt-etapa-5-baga-noves-de-segre.gpx"},
			{"ruta":"Bagà-Gresolet-Riu de Saldes", "fitxer":"baga-gresolet-riu_saldes.gpx"},
			{"ruta":"Bagà-Pla_Castell-Collada_Grossa-Refugi_Rebost-Millarès", "fitxer":"Baga-Pla_Castell-Collada_Grossa-Refugi_Rebost-Millares.gpx"},
			{"ruta":"Bagà, Brocà, Collada Grossa, Paller de Dalt, Paller de Baix, Bagà", "fitxer":"baga-broca-collada-grossa-paller-de-dalt-paller-de-baix-baga.gpx"}
		]}
	];

	return rutes;
}

export default llista_rutes;
